info:
  component: Config Samples
endpoints:
  restart:
    enabled: true
logging:
  level:
    hgfhg: DEBUG
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
